server:
  port: 9020
  servlet:
    context-path: /

spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8

  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8

      cache: false

  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mytmall?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: xieshuai
      # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initialSize: 5
      # 最小连接池数量
      minIdle: 5
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
       # 用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      validationQuery: SELECT 1 FROM DUAL
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnBorrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      # filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      # connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      # useGlobalDataSourceStat: true
  jpa:
      #指定数据库类型
      # database: mysql
      #控制台打印sql
      show-sql: true
      hibernate:
#        #表中字段命名策略,这里要引入hibernate的核心包，不然这个命名策略会报错
#         naming:
#           implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#           physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #建表策略，这里用update，即根据实体更新表结构
        ddl-auto: validate
      # 该属性将注册一个OpenEntityManagerInViewInterceptor，它将一个EntityManager注册到当前线程，因此您将拥有相同的EntityManager，直到Web请求完成。 它与Hibernate SessionFactory等无关。
      open-in-view: true
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
      #     #方言
      #     dialect: org.hibernate.dialect.MySQL5Dialect

  rabbitmq:
      host: 192.168.29.128
      port: 5672
#      virtual-host: /
      username: sherl
      password: sherl

# 日志配置
logging:
  level:
    root: info
#自定义配置
file-type:
  image:
    - .jpg
    - .jpeg
    - .png
    - .gif
#  music:
#  media: